"""initial schema

Revision ID: 08cbf41a4cf2
Revises: 
Create Date: 2026-08-25 04:48:06.319948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '08cbf41a4cf2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('given_name', sa.String(length=255), nullable=True),
    sa.Column('middle_name', sa.String(length=255), nullable=True),
    sa.Column('family_name', sa.String(length=255), nullable=True),
    sa.Column('suffix', sa.String(length=32), nullable=True),
    sa.Column('display_name', sa.String(length=512), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('sex', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('base_url', sa.String(length=2048), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_code'), 'sources', ['code'], unique=True)
    op.create_table('cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('case_status', sa.String(length=64), nullable=False),
    sa.Column('missing_date', sa.Date(), nullable=True),
    sa.Column('missing_city', sa.String(length=255), nullable=True),
    sa.Column('missing_county', sa.String(length=255), nullable=True),
    sa.Column('missing_state', sa.String(length=255), nullable=True),
    sa.Column('missing_country', sa.String(length=255), nullable=True),
    sa.Column('age_at_missing', sa.Integer(), nullable=True),
    sa.Column('circumstances', sa.Text(), nullable=True),
    sa.Column('investigating_agency', sa.String(length=255), nullable=True),
    sa.Column('agency_case_number', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cases_person_id'), 'cases', ['person_id'], unique=False)
    op.create_table('source_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'external_id', name='uq_source_records_source_id_external_id')
    )
    op.create_index(op.f('ix_source_records_source_id'), 'source_records', ['source_id'], unique=False)
    op.create_table('case_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('source_record_id', sa.Integer(), nullable=False),
    sa.Column('link_method', sa.String(length=64), nullable=False),
    sa.Column('link_confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['source_record_id'], ['source_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_sources_case_id'), 'case_sources', ['case_id'], unique=False)
    op.create_index(op.f('ix_case_sources_source_record_id'), 'case_sources', ['source_record_id'], unique=False)
    op.create_table('source_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_record_id', sa.Integer(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_record_id'], ['source_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_snapshots_source_record_id'), 'source_snapshots', ['source_record_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_source_snapshots_source_record_id'), table_name='source_snapshots')
    op.drop_table('source_snapshots')
    op.drop_index(op.f('ix_case_sources_source_record_id'), table_name='case_sources')
    op.drop_index(op.f('ix_case_sources_case_id'), table_name='case_sources')
    op.drop_table('case_sources')
    op.drop_index(op.f('ix_source_records_source_id'), table_name='source_records')
    op.drop_table('source_records')
    op.drop_index(op.f('ix_cases_person_id'), table_name='cases')
    op.drop_table('cases')
    op.drop_index(op.f('ix_sources_code'), table_name='sources')
    op.drop_table('sources')
    op.drop_table('people')
    # ### end Alembic commands ###
